name: xstream_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 2.0.1
homepage: https://github.com/caltek/xstream_player
documentation: https://github.com/caltek/xstream_player
repository: https://github.com/caltek/xstream_player
issue_tracker: https://github.com/caltek/xstream_player/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  equatable: ^2.0.7
  wakelock_plus: ^1.2.4
  path_provider: ^2.1.3
  visibility_detector: ^0.4.0+2
  crypto: ^3.0.6
  flutter_widget_from_html_core: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  plugin:
    platforms:
      android:
        package: uz.shs.better_player_plus
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin